# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cashflow_db
spring.datasource.username=postgres
spring.datasource.password=admin

# ===============================
# CONFIGURAÇÕES DO HIBERNATE (ORM)
# ===============================
# Essa é a linha mágica que cria as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está executando (ótimo para aprender)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar mais fácil de ler
spring.jpa.properties.hibernate.format_sql=true